### ISSUE TITLE
onReady callback sends undefined as first arg

### ISSUE THREAD

**Issue by mrspeaker** [npm-dom/youtube-video#3]
If you specify a callback, it gets called onReady: https://github.com/npm-dom/youtube-video/blob/master/index.js#L46
The first argument to the callback is hardcoded as `undefined`. Is there a reason for this? I don't really care (except I thought my code was broken ;)) - just wondering why.

**Comment by TehShrike** [comment]
I didn't write that part, but I assume it was done to conform to the popular [error-first callback style](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/).
